Repository cocos/cocos-engine, pull requests merged in 2022-03, with the labels that each got.

#10336 fix ios icon res lost
  native/templates/ios/CMakeLists.txt
Labels: contribution

#10333 v3.5.0 modify diffuseMap property visible
  cocos/core/scene-graph/scene-globals.ts
Labels: contribution

#10339 deferred shading code revert to 3.4.2
  editor/assets/chunks/standard-surface-entry.chunk
Labels: contribution

#10337 web pipeline can be enabled
  cocos/core/pipeline/custom/web-pipeline.ts
Labels: contribution

#10340 Rich text v align v3.5 #9984 new
  cocos/2d/components/rich-text.ts
  editor/i18n/en/localization.js
  editor/i18n/zh/localization.js
Labels: contribution

#10347 Fix shadow switching crash for v3.6.0
  native/cocos/scene/Shadow.cpp
Labels: contribution

#10351 [v3.6.0 pipeline] pipeline interface now uses gfx::Color only
  cocos/core/pipeline/custom/pipeline.ts
  cocos/core/pipeline/custom/web-pipeline.ts
  native/cocos/bindings/auto/jsb_render_auto.cpp
  native/cocos/renderer/pipeline/custom/NativePipelineImpl.cpp
  native/cocos/renderer/pipeline/custom/NativePipelineTypes.h
  native/cocos/renderer/pipeline/custom/RenderInterfaceTypes.h
Labels: contribution

#10350 Replace addPermanentRegisterCallback with addRegisterCallback.
  native/cocos/engine/Engine.cpp
Labels: contribution

#10360 Export Value in animation namespace
  cocos/core/animation/marionette/runtime-exports.ts
Labels: contribution

#10357 use approx instead of ===
  cocos/2d/framework/ui-transform.ts
Labels: contribution

#10362 Update native-compile-platforms.yml
  .github/workflows/automation_labels.yml
  .github/workflows/native-compile-platforms.yml
  .github/workflows/native-simulator.yml
  native/gulpfile.js
Labels: contribution

#10367 v3.6.0 sync Github Action
  .github/workflows/automation_labels.yml
  .github/workflows/native-compile-platforms.yml
  .github/workflows/native-simulator.yml
  native/gulpfile.js
Labels: contribution

#10390 UIOpacity Component DisallowMultiple
  cocos/2d/components/ui-opacity.ts
Labels: contribution

#10434 Fix templates and minor tweaks
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  cocos/2d/components/ui-mesh-renderer.ts
  cocos/core/assets/texture-cube.ts
  cocos/core/components/renderable-component.ts
  cocos/core/director.ts
Labels: Optimization

#10495 3.5 bugfix Android websocket send string
  native/cocos/network/WebSocket-okhttp.cpp
Labels: Bug

#10504 Fix label overflow shrink calculate font size error
  cocos2d/core/renderer/utils/label/ttf.js
Labels: PR: Cowboy merged
