Repository cocos/cocos-engine, pull requests merged in 2022-11, with the labels that each got.

#13195 Add tests for event-system
  native/CMakeLists.txt
  native/cocos/core/event/EventBus.cpp
  native/cocos/core/event/EventBus.h
  native/cocos/core/event/EventTarget.h
  native/cocos/core/event/intl/EventBusMacros.h
  native/cocos/core/event/intl/EventIntl.h
  native/tests/unit-test/src/core_event_bus.cpp
  native/tests/unit-test/src/core_event_target.cpp
Labels: Env: Native

#13178 fix toggle err function name
  cocos/ui/toggle.ts
Labels: contribution

#13328 fix:Downloader-java.cpp 's jni method nativeOnProgress/nativeOnFinish parameter type error
  native/cocos/network/Downloader-java.cpp
Labels: contribution

#13434 Mac: fix mouse wheel event
  native/cocos/platform/mac/View.mm
Labels: Bug

#13459 fix:when add multi xr video player only one is valid
  native/cocos/platform/android/libcocosxr/src/com/cocos/lib/xr/CocosXRVideoManager.java
  native/cocos/platform/android/libcocosxr/src/com/cocos/lib/xr/CocosXRVideoPlayer.java
Labels: contribution

#12280 fix: browser video-player doesnot emit click event
  cocos/video/video-player.ts
Labels: contribution

#11263 Fix composed character on multiline EditBox
  native/cocos/ui/edit-box/EditBox-ios.mm
Labels: contribution
