Repository cocos/cocos-engine, pull requests merged in 2022-09, with the labels that each got.

#12639 [v3.6.1] Fix jointTexture configuration not loaded on native platforms.
  cocos/core/root.jsb.ts
  native/cocos/core/Root.cpp
  native/cocos/renderer/pipeline/Define.cpp
  native/cocos/renderer/pipeline/Define.h
Labels: Bug, P1

#12659 3.6 genbindings abort on error
  native/external-config.json
  native/tools/tojs/genbindings.py
Labels: PR: Do not merge

#12690 improve:remove IXRInteraface's dependent from GFXDevice.h
  native/cocos/core/Root.cpp
  native/cocos/core/Root.h
  native/cocos/renderer/gfx-agent/DeviceAgent.cpp
  native/cocos/renderer/gfx-agent/DeviceAgent.h
  native/cocos/renderer/gfx-base/GFXDevice.cpp
  native/cocos/renderer/gfx-base/GFXDevice.h
  native/cocos/renderer/gfx-gles3/GLES3Device.cpp
  native/cocos/renderer/gfx-gles3/GLES3Device.h
  native/cocos/renderer/gfx-gles3/GLES3Swapchain.cpp
  native/cocos/renderer/gfx-gles3/GLES3Swapchain.h
  native/cocos/renderer/gfx-validator/DeviceValidator.cpp
  native/cocos/renderer/gfx-vulkan/VKDevice.cpp
  native/cocos/renderer/gfx-vulkan/VKDevice.h
  native/cocos/renderer/gfx-vulkan/VKGPUContext.cpp
  native/cocos/renderer/gfx-vulkan/VKSwapchain.cpp
  native/cocos/renderer/gfx-vulkan/VKSwapchain.h
  native/cocos/scene/Camera.cpp
  native/cocos/scene/Camera.h
Labels: contribution

#12374 v3.6.1 [fix] bmfont uv bug when overflow is clamp
  cocos/2d/assembler/label/bmfontUtils.ts
Labels: contribution

#12786 fix submeshes have different instancing options
  cocos/3d/framework/mesh-renderer.ts
  cocos/3d/models/baked-skinning-model.ts
  cocos/3d/models/skinning-model.ts
  cocos/core/pipeline/custom/executor.ts
  cocos/core/pipeline/deferred/gbuffer-stage.ts
  cocos/core/pipeline/forward/forward-stage.ts
  cocos/core/pipeline/instanced-buffer.ts
  cocos/core/pipeline/planar-shadow-queue.ts
  cocos/core/pipeline/render-additive-light-queue.ts
  cocos/core/pipeline/render-shadow-map-batched-queue.ts
  cocos/core/renderer/deprecated.ts
  cocos/core/renderer/scene/model.ts
  cocos/core/renderer/scene/submodel.ts
  native/cocos/3d/models/BakedSkinningModel.cpp
  native/cocos/3d/models/BakedSkinningModel.h
  native/cocos/3d/models/SkinningModel.cpp
  native/cocos/3d/models/SkinningModel.h
  native/cocos/bindings/manual/jsb_scene_manual.cpp
  native/cocos/renderer/pipeline/InstancedBuffer.cpp
  native/cocos/renderer/pipeline/InstancedBuffer.h
  native/cocos/renderer/pipeline/PlanarShadowQueue.cpp
  native/cocos/renderer/pipeline/PlanarShadowQueue.h
  native/cocos/renderer/pipeline/RenderAdditiveLightQueue.cpp
  native/cocos/renderer/pipeline/RenderAdditiveLightQueue.h
  native/cocos/renderer/pipeline/ShadowMapBatchedQueue.cpp
  native/cocos/renderer/pipeline/deferred/GbufferStage.cpp
  native/cocos/renderer/pipeline/forward/ForwardStage.cpp
  native/cocos/scene/Model.cpp
  native/cocos/scene/Model.h
  native/cocos/scene/SubModel.cpp
  native/cocos/scene/SubModel.h
  native/tools/tojs/scene.ini
Labels: Bug

#12844 fix:CC_ASSERT(!_currentApp.expired()); in WebSocketServer
  native/cocos/network/WebSocketServer.cpp
Labels: contribution

#12869 Feat: Expires bufferView after resizing it's source buffer.
  native/cocos/renderer/gfx-validator/BufferValidator.cpp
  native/cocos/renderer/gfx-validator/BufferValidator.h
  native/cocos/renderer/gfx-validator/DescriptorSetValidator.cpp
  native/cocos/renderer/gfx-vulkan/VKDescriptorSet.cpp
  native/cocos/renderer/pipeline/PipelineUBO.cpp
  native/cocos/renderer/pipeline/PipelineUBO.h
  native/cocos/renderer/pipeline/RenderAdditiveLightQueue.cpp
  native/cocos/renderer/pipeline/deferred/DeferredPipeline.cpp
  native/cocos/renderer/pipeline/forward/ForwardPipeline.cpp
  native/tools/swig-config/scene.i
Labels: Pipeline: Forward, Pipeline: Deferred

#12882 fix:WebSocket connection to 'ws://XXXX/' failed: A server must not ma…
  native/cocos/network/WebSocketServer.cpp
Labels: contribution, Env: Native, Module: Network

#12909 Added GFXDeviceObject.
  native/CMakeLists.txt
  native/cocos/renderer/gfx-base/GFXDeviceObject.h
  native/cocos/renderer/gfx-vulkan/VKCommandBuffer.cpp
  native/cocos/renderer/gfx-vulkan/VKCommandBuffer.h
  native/cocos/renderer/gfx-vulkan/VKCommands.cpp
  native/cocos/renderer/gfx-vulkan/VKDescriptorSet.cpp
  native/cocos/renderer/gfx-vulkan/VKDescriptorSet.h
  native/cocos/renderer/gfx-vulkan/VKDescriptorSetLayout.cpp
  native/cocos/renderer/gfx-vulkan/VKDescriptorSetLayout.h
  native/cocos/renderer/gfx-vulkan/VKFramebuffer.cpp
  native/cocos/renderer/gfx-vulkan/VKFramebuffer.h
  native/cocos/renderer/gfx-vulkan/VKGPUObjects.h
  native/cocos/renderer/gfx-vulkan/VKGPURecycleBin.cpp
  native/cocos/renderer/gfx-vulkan/VKInputAssembler.cpp
  native/cocos/renderer/gfx-vulkan/VKInputAssembler.h
  native/cocos/renderer/gfx-vulkan/VKPipelineLayout.cpp
  native/cocos/renderer/gfx-vulkan/VKPipelineLayout.h
  native/cocos/renderer/gfx-vulkan/VKPipelineState.cpp
  native/cocos/renderer/gfx-vulkan/VKPipelineState.h
  native/cocos/renderer/gfx-vulkan/VKQueryPool.cpp
  native/cocos/renderer/gfx-vulkan/VKQueryPool.h
  native/cocos/renderer/gfx-vulkan/VKRenderPass.cpp
  native/cocos/renderer/gfx-vulkan/VKRenderPass.h
  native/cocos/renderer/gfx-vulkan/VKShader.cpp
  native/cocos/renderer/gfx-vulkan/VKShader.h
Labels: GFX: Vulkan
