Repository cocos/cocos-engine, pull requests merged in 2022-05, with the labels that each got.

#10963 sphere i18n
  cocos/core/geometry/sphere.ts
  cocos/primitive/sphere.ts
Labels: PR: Cowboy merged

#10975 Remove unused code: defineOwnProperty("__native_ptr__",...)
  native/cocos/bindings/jswrapper/sm/Object.cpp
  native/cocos/bindings/jswrapper/v8/Object.cpp
Labels: Optimization

#10993 Add static property 'isJSBClass' for JSB classes and only enable it in DEBUG mode.
  native/tools/bindings-generator/targets/spidermonkey/templates/layout_head.c
  native/tools/bindings-generator/targets/spidermonkey/templates/register.c
Labels: Scripting

#11012 [JSB] Check whether node._children && node._children.length are valid in updateChildrenForDeserialize
  cocos/core/scene-graph/node.jsb.ts
  cocos/core/utils/jsb-utils.ts
Labels: Optimization

#10921 fix instanced model has not spot light shadow for v3.5.1
  cocos/core/pipeline/pipeline-ubo.ts
  cocos/core/pipeline/render-additive-light-queue.ts
  cocos/core/pipeline/render-batched-queue.ts
  cocos/core/pipeline/render-instanced-queue.ts
  cocos/core/pipeline/render-shadow-map-batched-queue.ts
  native/cocos/renderer/pipeline/RenderAdditiveLightQueue.cpp
  native/cocos/renderer/pipeline/RenderBatchedQueue.cpp
  native/cocos/renderer/pipeline/RenderBatchedQueue.h
  native/cocos/renderer/pipeline/RenderInstancedQueue.cpp
  native/cocos/renderer/pipeline/RenderInstancedQueue.h
Labels: PR: Do not merge

#11055 Scene should own RenderScene and camera needs to be detached in RenderScene::removeCamera.
  native/cocos/core/Types.h
  native/cocos/core/assets/RenderingSubMesh.h
  native/cocos/core/assets/Texture2D.cpp
  native/cocos/core/assets/Texture2D.h
  native/cocos/core/scene-graph/Scene.h
  native/cocos/scene/RenderScene.cpp
Labels: Bug, Module: Scene

#10925 Fix word wrap for Vietnamese characters
  cocos/2d/utils/text-utils.ts
Labels: contribution

#11137 `boost::hash_range` returns `size_t` which is 64bit on 64bit devices, so need to cast it to uint64_t.
  native/cocos/3d/assets/Mesh.cpp
  native/cocos/3d/assets/Skeleton.cpp
  native/cocos/core/assets/TextureBase.cpp
  native/cocos/core/assets/TextureBase.h
  native/cocos/scene/Pass.cpp
Labels: Bug

#11118 don't push data if debug is not enabled.
  cocos/core/animation/marionette/clip-motion.ts
Labels: contribution

#11246 fix 'Skin bone not found' tip
  cocos/spine/lib/spine-core.js
Labels: contribution
