Repository cocos/cocos-engine, pull requests merged in 2022-06, with the labels that each got.

#11325 [v3.6] Fix initial ref count for assets-manager.
  native/cocos/network/Downloader.h
  native/cocos/network/DownloaderImpl.h
  native/extensions/assets-manager/AssetsManagerEx.cpp
  native/extensions/assets-manager/AsyncTaskPool.cpp
Labels: Bug, P0

#11323 [v3.6] Don't rename webview& video c++ destuctor to destroy in webview/video.ini, add a 'destroy' method and bind it instead.
  native/cocos/ui/videoplayer/VideoPlayer-ios.mm
  native/cocos/ui/videoplayer/VideoPlayer-java.cpp
  native/cocos/ui/videoplayer/VideoPlayer.h
  native/cocos/ui/webview/WebView-inl.h
  native/cocos/ui/webview/WebView.h
  native/cocos/ui/webview/WebViewImpl-android.cpp
  native/cocos/ui/webview/WebViewImpl-ios.h
  native/cocos/ui/webview/WebViewImpl-ios.mm
  native/cocos/ui/webview/WebViewImpl-java.h
  native/cocos/ui/webview/WebViewImpl-ohos.cpp
  native/tools/tojs/video.ini
  native/tools/tojs/webview.ini
Labels: P1, Optimization

#11368 sevalue_to_native supports std::function<void()> and std::function<R()>, don't use attachObject to retain callback, use lambda to capture rooted callback se::Value instead.
  native/cocos/bindings/manual/jsb_conversions.h
Labels: Bug, P1

#11386 Change action run test cases
  .github/workflows/run_test_cases.yml
Labels: contribution

#11430 Fix that xcode 13 (c++17) treats deprecated warning as error.
  native/cmake/predefine.cmake
Labels: Bug

#11477 Fix the logic of fallback to 16 bits index buffer in Mesh.cpp, also fix memory leak if vertex count is less than 65536 on the platform which doesn't support ELEMENT_INDEX_UINT.
  native/cocos/3d/assets/Mesh.cpp
  native/cocos/base/RefVector.h
Labels: Bug, P1

#11523 [JSB] Fix some performance issues for 3.6.0 branch
  cc.config.json
  cocos/3d/framework/mesh-renderer.ts
  cocos/core/gfx/base/pipeline-state.jsb.ts
  cocos/core/gfx/index.jsb.ts
  native/cocos/bindings/jswrapper/v8/Object.cpp
  native/cocos/bindings/manual/jsb_scene_manual.cpp
  native/cocos/renderer/pipeline/InstancedBuffer.cpp
  native/cocos/scene/Model.cpp
  native/cocos/scene/Model.h
Labels: P1, Optimization

#11610 [update] update ral commit id
  platforms/runtime/target-commit.json
Labels: P1

#11609 fix can't dynamically require script on xiao platform
  scripts/bundle-adapter.js
Labels: P1

#11680 [v3.6] Fix that JS object is not in 'Weak' state if it is unrooted.
  native/cocos/bindings/jswrapper/v8/ObjectWrap.cpp
  native/cocos/bindings/jswrapper/v8/ObjectWrap.h
Labels: Bug, P1

#11740 Add macros: CC_USE_GEOMETRY_RENDERER and CC_USE_DEBUG_RENDERER to control these debugging features.
  native/CMakeLists.txt
  native/cocos/engine/Engine.cpp
  native/cocos/profiler/Profiler.cpp
  native/cocos/renderer/pipeline/GeometryRenderer.h
  native/cocos/renderer/pipeline/PipelineSceneData.cpp
  native/cocos/renderer/pipeline/RenderPipeline.cpp
  native/cocos/renderer/pipeline/RenderPipeline.h
  native/cocos/renderer/pipeline/custom/NativePipelineImpl.cpp
  native/cocos/renderer/pipeline/deferred/DeferredPipeline.cpp
  native/cocos/renderer/pipeline/deferred/LightingStage.cpp
  native/cocos/renderer/pipeline/deferred/PostProcessStage.cpp
  native/cocos/renderer/pipeline/forward/ForwardPipeline.cpp
  native/cocos/renderer/pipeline/forward/ForwardStage.cpp
  native/cocos/renderer/pipeline/helper/Utils.cpp
  native/cocos/renderer/pipeline/helper/Utils.h
  native/cocos/scene/Camera.cpp
  native/cocos/scene/Camera.h
  native/tools/bindings-generator/generator.py
  native/tools/bindings-generator/targets/spidermonkey/templates/ifunction.c
  native/tools/bindings-generator/targets/spidermonkey/templates/ifunction_overloaded.c
  native/tools/bindings-generator/targets/spidermonkey/templates/layout_foot.c
  native/tools/bindings-generator/targets/spidermonkey/templates/prelude.c
  native/tools/bindings-generator/targets/spidermonkey/templates/prelude.h
  native/tools/bindings-generator/targets/spidermonkey/templates/register.c
  native/tools/tojs/pipeline.ini
  native/tools/tojs/render.ini
  native/tools/tojs/scene.ini
  templates/common/CMakeLists.txt
Labels: P1, Env: Native

#11760 Don't depend on libuv, revert to use c++17 std::shared_mutex in ReadWriteLock.h
  native/cocos/base/threading/ReadWriteLock.h
Labels: P1, Optimization, Env: Native
