Repository cocos/cocos-engine, pull requests merged in 2023-08, with the labels that each got.

#15841 fix: terrain data lost when open prefab in editor
  cocos/terrain/terrain.ts
Labels: Editor

#15993 No longer output .ccon(b) extension
  cocos/asset/asset-manager/downloader.ts
  cocos/asset/asset-manager/editor-path-replace.ts
Labels: PR: Do not merge

#16023 [optimize] Remember connected gamepad count
  pal/input/web/gamepad-input.ts
Labels: Optimization
