Repository cocos/cocos-engine, pull requests merged in 2023-05, with the labels that each got.

#15108 Handle space conversion during pose graph evaluation, introduce base pose node class to modify pose
  cocos/animation/core/pose.ts
  cocos/animation/marionette/animation-graph-context.ts
  cocos/animation/marionette/graph-eval.ts
  cocos/animation/marionette/pose-graph/instantiation.ts
  cocos/animation/marionette/pose-graph/pose-node.ts
  cocos/animation/marionette/pose-graph/pose-nodes/modify-pose-base.ts
  cocos/animation/marionette/pose-graph/pose-nodes/transform-space.ts
  tests/animation/new-gen-anim/pose-graph/pose-nodes/single-pose-modifier.test.ts
  tests/animation/new-gen-anim/pose-graph/pose-nodes/utils/evaluation-mock.ts
  tests/animation/new-gen-anim/pose-graph/pose-transform-space.test.ts
  tests/animation/new-gen-anim/pose-graph/utils/helping-nodes/pose-node-map-pose-record.ts
  tests/animation/new-gen-anim/pose-graph/utils/helping-nodes/pose-node-modify-default-pose.ts
  tests/animation/new-gen-anim/utils/hierarchy-fixture.ts
  tests/animation/new-gen-anim/utils/pose-record.ts
  tests/animation/newgenanim.test.ts
Labels: PR: Cowboy merged

#15050 Animation graph: pose graph stash
  cocos/animation/core/pose-heap-allocator.ts
  cocos/animation/marionette/animation-graph-context.ts
  cocos/animation/marionette/animation-graph.ts
  cocos/animation/marionette/graph-eval.ts
  cocos/animation/marionette/pose-graph/default-top-level-pose-node.ts
  cocos/animation/marionette/pose-graph/pose-nodes/use-stashed-pose.ts
  cocos/animation/marionette/pose-graph/stash/runtime-stash.ts
  tests/animation/new-gen-anim/pose-graph/pose-nodes/stash-pose.test.ts
  tests/animation/new-gen-anim/pose-graph/pose-nodes/utils/evaluation-mock.ts
  tests/animation/new-gen-anim/pose-graph/pose-nodes/utils/factories/all.ts
  tests/animation/new-gen-anim/pose-graph/pose-nodes/utils/factories/use-stash-factory.ts
  tests/animation/new-gen-anim/utils/factory.ts
Labels: PR: Cowboy merged

#13625 fix tiled layer don't repaint when the camera has changed (position, size, etc.) .
  cocos/tiledmap/tiled-layer.ts
Labels: contribution

#13609 fix tiled map object node layer & tileset from atlas supported
  cocos/tiledmap/tiled-object-group.ts
  cocos/tiledmap/tiled-types.ts
  cocos/tiledmap/tiled-utils.ts
  cocos/tiledmap/tmx-xml-parser.ts
Labels: contribution

#14073 Windows devices input fix
  pal/input/web/mouse-input.ts
  pal/input/web/touch-input.ts
Labels: Needs Triage
